# Generated by Django 5.0.6 on 2024-05-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0002_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='Tournament.game'),
        ),
    ]
