# Generated by Django 5.0.6 on 2024-05-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0004_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='field_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
