# Generated by Django 5.0.6 on 2024-05-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0005_alter_player_field_goals_alter_player_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='average_score',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
