# Generated by Django 5.0.6 on 2024-05-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0006_player_average_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginactivity',
            name='duration',
        ),
    ]
