# Generated by Django 5.0.6 on 2024-05-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0009_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='average_score',
        ),
    ]
